class DBConnection:
    def __init__(self, path: str) -> None: ...
    def create_table(self, table_name: str) -> None: ...
    def show_tables(self) -> list[str]: ...
    def delete_table(self, table_name: str) -> None: ...
