class DBConnection:
    def __init__(self, path: str) -> None: ...
    def create_table(self, table_name: str) -> None: ...
    def show_tables(self) -> list[str]: ...
    def add_row(self, table_name: str, data: str) -> None: ...
    def delete_table(self, table_name: str) -> None: ...
    def get_rows(self, table_name: str) -> list[str]: ...
